λ> forM_
forM_ :: (Foldable t, Monad m) => t a -> (a -> m b) -> m ()
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10)
"Hello World!\n"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10)
"Hello World!\n"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10)
"Hello World!\n"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10)
"Hello World!\n"
λ> show (12, 'r')
"(12,'r')"
λ> show (12, 'r')
"(12,'r')"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10)
"('H',-762)('e',-767)('l',-775)('l',-776)('o',-780)(' ',-783)('W',-786)('o',-788)('r',-792)('l',-799)('d',-808)('!',-812)('\\n',-816)"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"('H',9228)('e',9223)('l',9215)('l',9214)('o',9210)(' ',9207)('W',9204)('o',9202)('r',9198)('l',9191)('d',9182)('!',9178)('\\n',9174)"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> "\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> topLevelEval (parseAndEval $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"('H',9228)('e',9223)('l',9215)('l',9214)('o',9210)(' ',9207)('W',9204)('o',9202)('r',9198)('l',9191)('d',9182)('!',9178)('\\n',9174)"
λ> topLevelEval (parseAndEval $ topLevelParse ",++++++++.") ("", 10)
"Failed on trying to Read at cnt=9"
λ> topLevelEval (parseAndEval $ topLevelParse ",++++++[++.") ("", 10)
"(line 1, column 12):\nunexpected end of input\nexpecting \">\", \"<\", \"+\", \"-\", \".\", \",\", \"[\" or \"]\""
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"('H',9228)('e',9223)('l',9215)('l',9214)('o',9210)(' ',9207)('W',9204)('o',9202)('r',9198)('l',9191)('d',9182)('!',9178)('\\n',9174)"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 10000)
"9174 : Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 9174)
"8348 : Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 9174)
"8348 : Hello World!\n"
λ> 10000 - 9174
826
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 826)
"0 : Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 826)
"0 : Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 824)
"*** Exception: /Users/cab/Dev/Haskell/parsers-interpr-in-haskell/brain-fck-interpreter/src/BFEvaluatorMTL.hs:(110,25)-(113,78): Non-exhaustive patterns in case

λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 824)
"Operation Counter run out before finishing the computation"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 826)
"0 : Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 826)
"0 : Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 826)
"0 : Hello World!\n"
λ> runStateT
runStateT :: StateT s m a -> s -> m (a, s)
λ> runStateT
runStateT :: StateT s m a -> s -> m (a, s)
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 826)
"0 : Hello World!\n"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 823)
"Operation Counter run out before finishing the computation, Std OutHello World!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 823)
"Operation Counter run out before finishing the computation, Std OutHello World!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 823)
"Hello World!\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 823)
"Hello World!\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test1.bfc"
"9622 : Hello World!"
λ> loadFile "test-cases/test2.bfc"
"9982 : bbb```"
λ> loadFile "test-cases/test3.bfc"
Interrupted.
λ> loadFile "test-cases/test2.bfc"
"9982 : bbb```"
λ> loadFile "test-cases/test2.bfc"
"9982 : bbb```"
λ> loadFile "test-cases/test2.bfc"
"9982 : bcdwxy"
λ> loadFile "test-cases/test2.bfc"
"9982 : bcdwxy"
λ> loadFile "test-cases/test1.bfc"
"9622 : Hello World!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 823)
"Hello World!\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 823)
"Hello World!\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 100)
"\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 500)
"\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"Hello Wo\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"Hello Wo\nPROCESS TIME OUT. KILLED!!!"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"Hello Wo\nPROCESS TIME OUT. KILLED!!!"
Cabal file changed: 874b0575f50b056cb035423507abbb1f
Restarting process ...
Hours of hacking await!
If I break, you can:
  1. Restart:           M-x haskell-process-restart
  2. Configure logging: C-h v haskell-process-log (useful for debugging)
  3. General config:    M-x customize-mode
  4. Hide these tips:   C-h v haskell-process-show-debug-tips
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> map ord "\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
[2,254,5,5,8,0,255,8,11,5,253,1,2]
λ> map ord "Hello World!"
[72,101,108,108,111,32,87,111,114,108,100,33]
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("AAAAA", 800)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> loadFile "test-cases/test3.bfc"
"sp"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("", 1000)
"\STX\254\ENQ\ENQ\b\NUL\255\b\v\ENQ\253\SOH\STX"
λ> topLevelEval (liftParse $ topLevelParse "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.") ("", 1000)
"Hello World!\n"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nop\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test12..bfc"
*** Exception: test-cases/test12..bfc: openFile: does not exist (No such file or directory)
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test-rot13.bfc"
"nopqrtuvwxyzabcdefghijklm\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test-rot11.bfc"
*** Exception: test-cases/test-rot11.bfc: openFile: does not exist (No such file or directory)
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklm\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test2.bfc"
"bcdwxy"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklm\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklm\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghij\nPROCESS TIME OUT. KILLED!!!"
λ> (=<<)
(=<<) :: Monad m => (a -> m b) -> m a -> m b
λ> (>>=)
(>>=) :: Monad m => m a -> (a -> m b) -> m b
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghij\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghij\nPROCESS TIME OUT. KILLED!!! 0"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghij\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! 0"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -2"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghij\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test1.bfc"
"Hello World!"
λ> loadFile "test-cases/test2.bfc"
"bcdwxy"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!! -1"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> :i intercalate
intercalate :: [a] -> [[a]] -> [a]
  	-- Defined in ‘base-4.12.0.0:Data.OldList’
λ> loadFile "test-cases/test13.bfc"
" \nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
" \nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test13.bfc"
"C\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"C\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test1.bfc"
"Hello World!"
λ> loadFile "test-cases/test2.bfc"
"bcdwxy"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOPQRS\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test123.bfc"
*** Exception: test-cases/test123.bfc: openFile: does not exist (No such file or directory)
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOPQRSTUVW\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOP\nPROCESS TIME OUT. KILLED!!!"

<interactive>:618:1-6: error: Variable not in scope: asdasd
Interrupted.

Some flags have not been recognized: prompt2, 
λ| λ| λ| λ| λ| λ| 
<interactive>:625:1: error: parse error on input ‘<’
λ> 
λ> 

<interactive>:618:1-6: error: Variable not in scope: asdasd
Interrupted.

Some flags have not been recognized: prompt2, 
λ| λ| λ| λ| λ| λ| 
<interactive>:635:1: error: parse error on input ‘<’
λ> 

<interactive>:618:1-6: error: Variable not in scope: asdasd
Interrupted.

Some flags have not been recognized: prompt2, 
λ| λ| λ| λ| λ| λ| 
<interactive>:644:1: error: parse error on input ‘<’
λ> 
λ> 
λ> 
λ> 2+2
4
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test13.bfc"
"C\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"C\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklm\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklm\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijkl\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklm\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test13.bfc"
"Cp"
λ> loadFile "test-cases/test12.bfc"
"Co"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmNOPQRSTUVW\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghi\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghi\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test13.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test12.bfc"
"\nPROCESS TIME OUT. KILLED!!!"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test2.bfc"
"bcdwxy"
λ> loadFile "test-cases/test2.bfc"
"bcdwxy99982"
λ> run "++[.-]" ""
"\STX\SOH99986"
λ> topLevelEval "++[.-]" ""
"\STX\SOH"
λ> topLevelEval "++[.-]" ""
"\STX\SOH99990"
λ> run "++[.-]" ""
"\STX\SOH99986"
λ> run "++" ""
"99998"
λ> run "[]" ""
"99996"
λ> run "[]" ""
"99997"
λ> topLevelEval "[]" ""
"99998"
λ> run "[]" ""
"99997"
λ> run "[]" ""
"99998"
λ> run "[]" ""
"99998"
λ> run "++" ""
"99998"
λ> run "++[.-]" ""
"\STX\SOH99991"
λ> run "[]" ""
"99997"
λ> run "[]" ""
"99998"
λ> run "++[.-]" ""
"\STX\SOH99988"
λ> run "+[.-]" ""
"\SOH99993"
λ> run "+" ""
"99999"
λ> run "+[]" ""
"\nPROCESS TIME OUT. KILLED!!!-1"
λ> run "+-[]" ""
"99996"
λ> run "+[.-]" ""
"\SOH99993"
λ> run "+[.-]" ""
"\SOH99995"
λ> run "+[.-]" ""
"\SOH99995"
λ> run "++[.-]" ""
"\STX\SOH99992"
λ> run "++[.-]" ""
"\STX\SOH99988"
λ> run "++[.-]" ""
"\STX\SOH99992"
λ> run "++[.-]" ""
"\STX\SOH99992"
λ> run "+++[.-]" ""
"\ETX\STX\SOH99989"
λ> run "++[.-]" ""
"\STX\SOH99992"
λ> run "+++[.-]" ""
"\ETX\STX\SOH99989"
λ> run "+++[.-]" ""
"\ETX\STX\SOH99983"
λ> run "++[.-]" ""
"\STX\SOH99988"
λ> run "+[.-]" ""
"\SOH99993"
λ> run "+[.-]" ""
"\SOH99993"
λ> run "+[.-]" ""
"\SOH99995"
λ> run "++[.-]" ""
"\STX\SOH99990"
λ> run "+++[.-]" ""
"\ETX\STX\SOH99985"
λ> loadFile "test-cases/test1.bfc"
"Hello World!99603"
λ> loadFile "test-cases/test2.bfc"
"bcdwxy99982"
λ> loadFile "test-cases/test3.bfc"

*** Exception: stInterrupted.
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test12.bfc"
"Co0"
λ> loadFile "test-cases/test13.bfc"
"Cp-1"
λ> loadFile "test-cases/test3.bfc"
*** ExcInterrupted.
λ> loadFile "test-cases/test13.bfc"
"C-1"
λ> loadFile "test-cases/test12.bfc"
"Co0"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test13.bfc"
"Cp-1"
λ> loadFile "test-cases/test13.bfc"
"C-1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test12.bfc"
"Co0"
λ> loadFile "test-cases/test12.bfc"
"Co0"
λ> loadFile "test-cases/test13.bfc"
"C-1"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!-1"
λ> loadFile "test-cases/test3.bfc"
"sp\nPROCESS TIME OUT. KILLED!!!0"
λ> loadFile "test-cases/test13.bfc"
"C\nPROCESS TIME OUT. KILLED!!!0"
λ> loadFile "test-cases/test12.bfc"
"Co0"
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!0"
λ> (<$>)
(<$>) :: Functor f => (a -> b) -> f a -> f b
λ> fmap
fmap :: Functor f => (a -> b) -> f a -> f b
λ> :i (<$>)
(<$>) :: Functor f => (a -> b) -> f a -> f b
  	-- Defined in ‘Data.Functor’
infixl 4 <$>
λ> (,)
(,) :: a -> b -> (a, b)
λ> 
λ> loadFile "test-cases/test11.bfc"
"nopqrtuvwxyzabcdefghijklmN\nPROCESS TIME OUT. KILLED!!!0"
λ> loadFile "test-cases/test12.bfc"
"Co0"
λ> loadFile "test-cases/test13.bfc"
"C\nPROCESS TIME OUT. KILLED!!!0"
λ> 
